@protocol=http://
@host=localhost
@port=:2600
@prefix=
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Reception de toutes les balades
GET {{baseUrl}}/rides

### Suppression d'une balade
DELETE {{baseUrl}}/ride/6

### Retirer un membre d'une balade
DELETE {{baseUrl}}/ride/2/participation


### Retirer un membre d'une balade dont on est l'orga
DELETE {{baseUrl}}/ride/1/participation/user/3

