@protocol=http://
@host=localhost
@port=:2600
@prefix=
@baseUrl={{protocol}}{{host}}{{port}}{{prefix}}

### Suppresion d'une balade
DELETE {{baseUrl}}/ride/6

### Retirer un membre d'une balade
DELETE {{baseUrl}}/ride/8/participation

### Ajout un nouveau membre à une balade
POST {{baseUrl}}/ride/2/participation
